// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwO35eqT2ntyNbO2Qid7JNsthkBUmiWuc',
    appId: '1:385039552808:web:0474760cdf15c264e4001d',
    messagingSenderId: '385039552808',
    projectId: 'geekdin-f7049',
    authDomain: 'geekdin-f7049.firebaseapp.com',
    storageBucket: 'geekdin-f7049.firebasestorage.app',
    measurementId: 'G-CE5GVLN043',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmq9Cv55mi30JI_EhrYYpByBMlxjthzxw',
    appId: '1:385039552808:android:f9523cbd48cff5d3e4001d',
    messagingSenderId: '385039552808',
    projectId: 'geekdin-f7049',
    storageBucket: 'geekdin-f7049.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvxVrD18YR_TrSdDBos00VhtI4l3O3RwM',
    appId: '1:385039552808:ios:fcaa1897a4feb23be4001d',
    messagingSenderId: '385039552808',
    projectId: 'geekdin-f7049',
    storageBucket: 'geekdin-f7049.firebasestorage.app',
    iosBundleId: 'com.example.geekdin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvxVrD18YR_TrSdDBos00VhtI4l3O3RwM',
    appId: '1:385039552808:ios:fcaa1897a4feb23be4001d',
    messagingSenderId: '385039552808',
    projectId: 'geekdin-f7049',
    storageBucket: 'geekdin-f7049.firebasestorage.app',
    iosBundleId: 'com.example.geekdin',
  );
}
